alias ls="ls -AFG"
alias mv="mv -i"
alias ln="ln -i"
alias btc="telnet ticker.bitcointicker.co 10080"
alias btctrade="python ~/.dotfiles/scripts/BTCTrade.py"
alias mgemi="cd /Users/Ari/M.\ Gemi/git/demandware-mgemi"
alias scrutinize="SCRUTINY_HOST=dev02 /Users/Ari/M.\ Gemi/git/demandware-mgemi/bin/scrutinize"
alias confidence="python ~/.dotfiles/scripts/Confidence.py"
alias apt-get="brew"
alias matrix="cmatrix"
alias master="git checkout master"
alias dev="git checkout development"
