#!/usr/bin/env sh

# Detect the current shell
if [ -n "$ZSH_VERSION" ]; then
    CURRENT_SHELL="zsh"
elif [ -n "$BASH_VERSION" ]; then
    CURRENT_SHELL="bash"
else
    CURRENT_SHELL="sh"
fi

{
echo "Pushing dotfiles directory"
pushd ~/.dotfiles/ > /dev/null 2>&1 || exit

# Source all .sh files
for script in *.sh; do
    if [ -f "$script" ]; then
        echo "Executing $script"
        source "./$script"
    fi
done

echo "Popping dotfiles directory"
popd > /dev/null 2>&1 || exit
} 1>~/.dotfiles/load.out 2>~/.dotfiles/load.err
